##########################################################
##            Default environment yaml file             ##
##########################################################
# NOTE: See validation_templates/environment_template.py # 
#       for the parameter restrictions.                   #
##########################################################

window_dimensions : [1280, 720]
background:
    sprite : "assets/background_C_Lelant.png"
