#####################################################
##            Default target yaml file             ##
#####################################################
# NOTE: See validation_templates/target_template.py # 
#       for the parameter restrictions              #
#####################################################

sprite : "assets/target.png"
size : [40, 40]
position : [800, 500] # coordinate of top left most pixel
coll_radius : 20 # amount of pixels around position used for collision
